package exercise12_B;

import java.util.ArrayList;
import java.util.List;
public class MainApp {
	public static void main(String args[])
	{
		
		List <Student> list = new ArrayList <Student> ();
		
		//making student objects
		Student s1 = new Student(1,"Soham","Panaji");
		Student s2 = new Student(2,"Raju","Mapusa");
		Student s3 = new Student(3,"Rahul","Margao");
		Student s4 = new Student(4,"Meena","Raia");
		Student s5 = new Student(5,"Ashok","Vasco");
		Student s6 = new Student(6,"Shyam","Ponda");
		Student s7 = new Student(6,"Ram","Cuncolim");
		
		//students enrolled in course c1
		list.add(s1);
		list.add(s2);
		Course c1 = new Course("Goa University",20,"GovtCollege",1,"Science",1,"Bsc CS",true,19000f,3,list);
		list.clear();
		
		//students enrolled in course c2
		list.add(s3);
		list.add(s4);
		Course c2 = new Course("Goa University",21,"GovtCollege",1,"Science",10,"BCA",true,50000f,3,list);
		list.clear();
		//students enrolled in course c3
		list.add(s5);
		list.add(s6);
		Course c3 = new Course("Goa University",0,"",2,"Commerce",11,"Bcom",true,11000f,3,list);
		list.clear();
		
		list.add(s7);
		Course c4 = new Course("Goa University",0,"",3,"Arts",12,"BA",true,12000f,3,list);
		list.clear();
		
		System.out.println("No of Students enrolled in each course in University & affliated colleges  :- \n");
		c1.display();
		c2.display();
		c3.display();
		c4.display();
		
		System.out.println("\nNo of Students enrolled in each course across University are :- ");
		c1.display2();
		c2.display2();
		c3.display2();
		c4.display2();
		
		System.out.println("\n\nRevenue Generated by each Course in University:- ");
		c1.uniRevenue();
		c2.uniRevenue();
		c3.uniRevenue();
		c4.uniRevenue();
	}
}
